[package]
name = "vita"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
memory = { path = "../memory" }
interoception = { path = "../interoception" }
scheduler = { path = "../scheduler" }
senses = { path = "../senses" }
kv-controller = { path = "../kv-controller" }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
