//! Skill and tool provenance — who authored it, when, and lifecycle state.

use serde::{Deserialize, Serialize};

// ── SkillAuthor ───────────────────────────────────────────────────────────────

/// Identifies who authored a skill or tool artifact.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum SkillAuthor {
    /// Shipped with the AnimaOS binary.  Read-only, versioned with the repo.
    Builtin,
    /// Written directly by a human operator.
    Operator,
    /// Generated by the agent during the dreaming or consolidation sleep phase.
    Agent,
}

impl core::fmt::Display for SkillAuthor {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            SkillAuthor::Builtin => write!(f, "builtin"),
            SkillAuthor::Operator => write!(f, "operator"),
            SkillAuthor::Agent => write!(f, "agent"),
        }
    }
}

// ── SkillProvenance ───────────────────────────────────────────────────────────

/// Immutable provenance record attached to every skill and tool.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct SkillProvenance {
    /// Who created this artifact.
    pub authored_by: SkillAuthor,
    /// Unix nanoseconds at proposal time (`0` for built-ins).
    pub proposed_at_ns: u64,
    /// Episode that motivated the proposal, if authored by the agent.
    pub source_episode: Option<String>,
    /// SKILL.md schema version at creation time.
    pub schema_version: u32,
}

impl SkillProvenance {
    /// Provenance for a built-in skill.
    pub fn builtin() -> Self {
        SkillProvenance {
            authored_by: SkillAuthor::Builtin,
            proposed_at_ns: 0,
            source_episode: None,
            schema_version: 1,
        }
    }

    /// Provenance for an operator-authored skill.
    pub fn operator(proposed_at_ns: u64) -> Self {
        SkillProvenance {
            authored_by: SkillAuthor::Operator,
            proposed_at_ns,
            source_episode: None,
            schema_version: 1,
        }
    }

    /// Provenance for an agent-authored skill.
    pub fn agent(proposed_at_ns: u64, episode_id: impl Into<String>) -> Self {
        SkillProvenance {
            authored_by: SkillAuthor::Agent,
            proposed_at_ns,
            source_episode: Some(episode_id.into()),
            schema_version: 1,
        }
    }
}

// ── SkillState ────────────────────────────────────────────────────────────────

/// Lifecycle state of a skill in the registry.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub enum SkillState {
    /// Available for selection in cortex context.
    Active,
    /// Registered but awaiting operator approval before activation.
    Proposed,
    /// Temporarily blocked; circuit-breaker tripped or defence flag raised.
    Quarantined {
        /// Human-readable reason for quarantine.
        reason: String,
    },
    /// Rolled back to a prior version; no longer active.
    RolledBack,
}

impl SkillState {
    /// `true` when the skill may be presented to the cortex.
    pub fn is_active(&self) -> bool {
        matches!(self, SkillState::Active)
    }

    /// `true` when the skill is awaiting operator approval.
    pub fn is_proposed(&self) -> bool {
        matches!(self, SkillState::Proposed)
    }

    /// `true` when the skill is quarantined.
    pub fn is_quarantined(&self) -> bool {
        matches!(self, SkillState::Quarantined { .. })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn active_state_is_active() {
        assert!(SkillState::Active.is_active());
        assert!(!SkillState::Proposed.is_active());
        assert!(!SkillState::RolledBack.is_active());
    }

    #[test]
    fn quarantined_state_is_quarantined() {
        let q = SkillState::Quarantined {
            reason: "defence flag".to_string(),
        };
        assert!(q.is_quarantined());
        assert!(!q.is_active());
    }

    #[test]
    fn provenance_builtin_has_zero_timestamp() {
        let p = SkillProvenance::builtin();
        assert_eq!(p.authored_by, SkillAuthor::Builtin);
        assert_eq!(p.proposed_at_ns, 0);
    }

    #[test]
    fn provenance_agent_carries_episode_id() {
        let p = SkillProvenance::agent(12345, "ep-42");
        assert_eq!(p.authored_by, SkillAuthor::Agent);
        assert_eq!(p.source_episode.as_deref(), Some("ep-42"));
    }
}
