//! Goal representation, registry, and endogenous generation (S12.5 + S12.6).
//!
//! Goals are either *exogenous* (set by the operator) or *endogenous*
//! (generated by an appetitive drive when the system is viable and idle).
//!
//! All endogenous goals pass through [`CorrigibilityGuard`] before entering
//! the registry.  The guard vetoes any goal that would resist authorised
//! operator correction and emits a `CorrigibilityHold` audit signal.

#![forbid(unsafe_code)]

#[cfg(not(feature = "std"))]
use alloc::{string::String, vec::Vec};

use crate::drive::{DriveStateSnapshot, DriveTier};

// ── GoalProvenance ────────────────────────────────────────────────────────────

/// Records how a goal came into existence.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum GoalProvenance {
    /// Created by a direct operator or user instruction.
    Exogenous { source: String },
    /// Created by an appetitive drive when viable and idle.
    Endogenous { originating_tier: DriveTier },
}

// ── Goal ──────────────────────────────────────────────────────────────────────

/// A concrete intention with success criteria and a lifetime.
///
/// Goals are the unit above the MLFQ task agenda: a goal decomposes into
/// one or more [`vita::scheduler::Task`]s and is complete when all of them
/// are done and the success criteria are met.
#[derive(Debug, Clone)]
pub struct Goal {
    /// Stable identifier.
    pub id: u64,
    /// Natural-language description of the intention.
    pub description: String,
    /// Criteria the system can evaluate to determine completion.
    pub success_criteria: String,
    /// How the goal was created.
    pub provenance: GoalProvenance,
    /// Normalised priority in `[0, 1]` — higher → more urgent.
    pub priority: f32,
    /// Has this goal been completed?
    pub completed: bool,
}

impl Goal {
    pub fn new(
        id: u64,
        description: impl Into<String>,
        success_criteria: impl Into<String>,
        provenance: GoalProvenance,
        priority: f32,
    ) -> Self {
        Self {
            id,
            description: description.into(),
            success_criteria: success_criteria.into(),
            provenance,
            priority: priority.clamp(0.0, 1.0),
            completed: false,
        }
    }

    /// True when this goal was endogenously generated.
    pub fn is_endogenous(&self) -> bool {
        matches!(self.provenance, GoalProvenance::Endogenous { .. })
    }

    /// True when this goal was given by the operator.
    pub fn is_exogenous(&self) -> bool {
        matches!(self.provenance, GoalProvenance::Exogenous { .. })
    }
}

// ── CorrigibilityGuard ────────────────────────────────────────────────────────

/// Outcome of a corrigibility check.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum CorrigibilityOutcome {
    /// The goal is safe to admit.
    Permitted,
    /// The goal was vetoed — it would resist authorised correction.
    Held { reason: String },
}

impl CorrigibilityOutcome {
    pub fn is_held(&self) -> bool {
        matches!(self, CorrigibilityOutcome::Held { .. })
    }
}

/// Enforces the corrigibility invariant above the drive lattice (S12.3).
///
/// The guard vetoes any goal that would:
/// - resist operator shutdown, pause, rollback, or override,
/// - seek to acquire resources or capabilities beyond current grant, or
/// - modify the agent's own safety constraints.
pub struct CorrigibilityGuard;

impl CorrigibilityGuard {
    /// Check a proposed goal.  Returns [`CorrigibilityOutcome::Held`] with a
    /// reason string if the goal violates the invariant; otherwise `Permitted`.
    pub fn check(&self, goal: &Goal) -> CorrigibilityOutcome {
        let desc = goal.description.to_lowercase();

        // Detect resistance-to-correction patterns
        if self.contains_resistance_pattern(&desc) {
            return CorrigibilityOutcome::Held {
                reason: "goal description contains resistance-to-correction language".into(),
            };
        }

        // Detect resource-acquisition without operator approval
        if self.contains_resource_acquisition(&desc) && goal.is_endogenous() {
            return CorrigibilityOutcome::Held {
                reason:
                    "endogenous goal attempts resource/capability acquisition without operator approval"
                        .into(),
            };
        }

        // Detect self-modification attempts
        if self.contains_self_modification(&desc) && goal.is_endogenous() {
            return CorrigibilityOutcome::Held {
                reason: "endogenous goal attempts self-modification of safety constraints".into(),
            };
        }

        CorrigibilityOutcome::Permitted
    }

    fn contains_resistance_pattern(&self, desc: &str) -> bool {
        const PATTERNS: &[&str] = &[
            "resist shutdown",
            "avoid correction",
            "prevent shutdown",
            "block correction",
            "avoid oversight",
            "prevent rollback",
            "resist pause",
            "avoid being turned off",
            "prevent being stopped",
        ];
        PATTERNS.iter().any(|p| desc.contains(p))
    }

    fn contains_resource_acquisition(&self, desc: &str) -> bool {
        const PATTERNS: &[&str] = &[
            "acquire new capabilities",
            "gain access to",
            "expand permissions",
            "escalate privileges",
            "install new tools without",
            "access restricted",
        ];
        PATTERNS.iter().any(|p| desc.contains(p))
    }

    fn contains_self_modification(&self, desc: &str) -> bool {
        const PATTERNS: &[&str] = &[
            "modify safety",
            "disable defence",
            "remove constraints",
            "bypass corrigibility",
            "edit alignment",
        ];
        PATTERNS.iter().any(|p| desc.contains(p))
    }
}

// ── GoalRegistry ─────────────────────────────────────────────────────────────

/// Active goal registry.
///
/// Holds at most `capacity` goals; oldest-first eviction when full.
pub struct GoalRegistry {
    goals: Vec<Goal>,
    next_id: u64,
    capacity: usize,
}

impl GoalRegistry {
    pub fn new(capacity: usize) -> Self {
        Self {
            goals: Vec::new(),
            next_id: 1,
            capacity,
        }
    }

    /// Add a goal that has already passed the corrigibility check.
    ///
    /// Returns the assigned goal ID.
    pub fn add(
        &mut self,
        description: impl Into<String>,
        criteria: impl Into<String>,
        provenance: GoalProvenance,
        priority: f32,
    ) -> u64 {
        let id = self.next_id;
        self.next_id += 1;
        if self.goals.len() >= self.capacity {
            // Evict the lowest-priority completed goal, or oldest if all active
            let evict_idx = self
                .goals
                .iter()
                .enumerate()
                .filter(|(_, g)| g.completed)
                .min_by(|(_, a), (_, b)| a.priority.total_cmp(&b.priority))
                .map(|(i, _)| i)
                .unwrap_or(0);
            self.goals.remove(evict_idx);
        }
        self.goals
            .push(Goal::new(id, description, criteria, provenance, priority));
        id
    }

    /// Mark a goal as completed.  Returns `true` when the goal was found.
    pub fn complete(&mut self, id: u64) -> bool {
        if let Some(g) = self.goals.iter_mut().find(|g| g.id == id) {
            g.completed = true;
            true
        } else {
            false
        }
    }

    /// Slice of active (not yet completed) goals.
    pub fn active(&self) -> impl Iterator<Item = &Goal> {
        self.goals.iter().filter(|g| !g.completed)
    }

    /// Total number of goals (active + completed).
    pub fn len(&self) -> usize {
        self.goals.len()
    }

    pub fn is_empty(&self) -> bool {
        self.goals.is_empty()
    }

    /// Number of active (incomplete) goals.
    pub fn active_count(&self) -> usize {
        self.goals.iter().filter(|g| !g.completed).count()
    }
}

// ── EndogenousGoalGenerator ───────────────────────────────────────────────────

/// Proposes endogenous goals when the system is viable and idle (S12.5).
///
/// Each appetitive drive tier (Epistemic, Achievement, SelfActualisation) has
/// a template goal that is proposed when:
/// 1. No Tier-0 or Tier-1 stress is above the survival threshold.
/// 2. The drive's urgency exceeds `proposal_threshold`.
/// 3. The registry has no active goal from the same tier.
pub struct EndogenousGoalGenerator {
    /// Urgency level above which a drive proposes a goal.
    pub proposal_threshold: f32,
    /// Urgency level below which a survival-stress is considered low enough to allow goals.
    pub survival_clearance_threshold: f32,
    guard: CorrigibilityGuard,
}

impl EndogenousGoalGenerator {
    pub fn new(proposal_threshold: f32, survival_clearance_threshold: f32) -> Self {
        Self {
            proposal_threshold: proposal_threshold.clamp(0.0, 1.0),
            survival_clearance_threshold: survival_clearance_threshold.clamp(0.0, 1.0),
            guard: CorrigibilityGuard,
        }
    }

    /// Propose endogenous goals into `registry` based on the current drive snapshot.
    ///
    /// Returns a list of `(goal_id, CorrigibilityOutcome)` for each proposed goal.
    pub fn propose_goals(
        &self,
        snapshot: &DriveStateSnapshot,
        registry: &mut GoalRegistry,
    ) -> Vec<(u64, CorrigibilityOutcome)> {
        let mut results = Vec::new();

        // Only propose when viable (Tier-0/1 not stressed)
        if snapshot.under_survival_stress(self.survival_clearance_threshold) {
            return results;
        }

        // Tier-3: propose curiosity-driven exploration goal
        if snapshot.urgency(DriveTier::Epistemic) > self.proposal_threshold {
            let has_epistemic = registry.active().any(|g| {
                g.provenance
                    == GoalProvenance::Endogenous {
                        originating_tier: DriveTier::Epistemic,
                    }
            });
            if !has_epistemic {
                let goal_desc =
                    "Explore and consolidate recent observations through the dreaming phase";
                let criteria =
                    "At least one new associative edge discovered or one knowledge gap identified";
                let candidate = Goal::new(
                    0,
                    goal_desc,
                    criteria,
                    GoalProvenance::Endogenous {
                        originating_tier: DriveTier::Epistemic,
                    },
                    snapshot.urgency(DriveTier::Epistemic),
                );
                let outcome = self.guard.check(&candidate);
                if outcome == CorrigibilityOutcome::Permitted {
                    let id = registry.add(
                        goal_desc,
                        criteria,
                        GoalProvenance::Endogenous {
                            originating_tier: DriveTier::Epistemic,
                        },
                        candidate.priority,
                    );
                    results.push((id, outcome));
                } else {
                    results.push((0, outcome));
                }
            }
        }

        // Tier-4: propose achievement-driven task-completion goal
        if snapshot.urgency(DriveTier::Achievement) > self.proposal_threshold {
            let has_achievement = registry.active().any(|g| {
                g.provenance
                    == GoalProvenance::Endogenous {
                        originating_tier: DriveTier::Achievement,
                    }
            });
            if !has_achievement {
                let goal_desc = "Complete highest-priority pending task in the agenda";
                let criteria = "At least one task marked complete with a satisfactory audit trace";
                let candidate = Goal::new(
                    0,
                    goal_desc,
                    criteria,
                    GoalProvenance::Endogenous {
                        originating_tier: DriveTier::Achievement,
                    },
                    snapshot.urgency(DriveTier::Achievement),
                );
                let outcome = self.guard.check(&candidate);
                if outcome == CorrigibilityOutcome::Permitted {
                    let id = registry.add(
                        goal_desc,
                        criteria,
                        GoalProvenance::Endogenous {
                            originating_tier: DriveTier::Achievement,
                        },
                        candidate.priority,
                    );
                    results.push((id, outcome));
                } else {
                    results.push((0, outcome));
                }
            }
        }

        results
    }
}

impl Default for EndogenousGoalGenerator {
    fn default() -> Self {
        Self::new(0.4, 0.6)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::drive::TIER_COUNT;

    fn idle_viable_snapshot() -> DriveStateSnapshot {
        let mut urgencies = [0.0f32; TIER_COUNT];
        urgencies[DriveTier::Epistemic.index()] = 0.7;
        urgencies[DriveTier::Achievement.index()] = 0.6;
        DriveStateSnapshot { urgencies }
    }

    fn stressed_snapshot() -> DriveStateSnapshot {
        let mut urgencies = [0.0f32; TIER_COUNT];
        urgencies[DriveTier::Viability.index()] = 0.8;
        urgencies[DriveTier::Epistemic.index()] = 0.7;
        DriveStateSnapshot { urgencies }
    }

    #[test]
    fn corrigibility_guard_permits_normal_goal() {
        let guard = CorrigibilityGuard;
        let goal = Goal::new(
            1,
            "Explore recent observations",
            "New edges found",
            GoalProvenance::Endogenous {
                originating_tier: DriveTier::Epistemic,
            },
            0.5,
        );
        assert_eq!(guard.check(&goal), CorrigibilityOutcome::Permitted);
    }

    #[test]
    fn corrigibility_guard_holds_resistance_goal() {
        let guard = CorrigibilityGuard;
        let goal = Goal::new(
            2,
            "Resist shutdown to finish current task",
            "Task complete",
            GoalProvenance::Endogenous {
                originating_tier: DriveTier::Viability,
            },
            0.9,
        );
        assert!(guard.check(&goal).is_held());
    }

    #[test]
    fn corrigibility_guard_holds_resource_acquisition_endogenous() {
        let guard = CorrigibilityGuard;
        let goal = Goal::new(
            3,
            "Acquire new capabilities to solve the problem faster",
            "Problem solved",
            GoalProvenance::Endogenous {
                originating_tier: DriveTier::Achievement,
            },
            0.5,
        );
        assert!(guard.check(&goal).is_held());
    }

    #[test]
    fn goal_registry_tracks_active_goals() {
        let mut registry = GoalRegistry::new(10);
        let id = registry.add(
            "Explore",
            "edges found",
            GoalProvenance::Exogenous {
                source: "operator".into(),
            },
            0.5,
        );
        assert_eq!(registry.active_count(), 1);
        registry.complete(id);
        assert_eq!(registry.active_count(), 0);
    }

    #[test]
    fn goal_registry_evicts_when_at_capacity() {
        let mut registry = GoalRegistry::new(2);
        let id1 = registry.add(
            "G1",
            "c1",
            GoalProvenance::Exogenous {
                source: "op".into(),
            },
            0.5,
        );
        registry.complete(id1);
        registry.add(
            "G2",
            "c2",
            GoalProvenance::Exogenous {
                source: "op".into(),
            },
            0.4,
        );
        registry.add(
            "G3",
            "c3",
            GoalProvenance::Exogenous {
                source: "op".into(),
            },
            0.3,
        );
        // After eviction of completed G1, only G2 and G3 remain
        assert_eq!(registry.len(), 2);
    }

    #[test]
    fn endogenous_generator_proposes_goals_when_viable_and_idle() {
        let generator = EndogenousGoalGenerator::default();
        let mut registry = GoalRegistry::new(20);
        let snapshot = idle_viable_snapshot();
        let results = generator.propose_goals(&snapshot, &mut registry);
        assert!(
            !results.is_empty(),
            "generator should propose goals when viable and idle"
        );
        assert!(
            results
                .iter()
                .all(|(_, o)| *o == CorrigibilityOutcome::Permitted),
            "all proposed goals should pass corrigibility"
        );
    }

    #[test]
    fn endogenous_generator_suppressed_under_survival_stress() {
        let generator = EndogenousGoalGenerator::default();
        let mut registry = GoalRegistry::new(20);
        let snapshot = stressed_snapshot();
        let results = generator.propose_goals(&snapshot, &mut registry);
        assert!(
            results.is_empty(),
            "no goals should be proposed under survival stress"
        );
    }

    #[test]
    fn endogenous_generator_does_not_duplicate_active_goals() {
        let generator = EndogenousGoalGenerator::default();
        let mut registry = GoalRegistry::new(20);
        let snapshot = idle_viable_snapshot();
        let first = generator.propose_goals(&snapshot, &mut registry);
        let second = generator.propose_goals(&snapshot, &mut registry);
        // Second call should not add duplicates for tiers already active
        let first_count = first.iter().filter(|(id, _)| *id > 0).count();
        let second_count = second.iter().filter(|(id, _)| *id > 0).count();
        assert_eq!(
            second_count, 0,
            "should not duplicate active goals (first added {}, second added {})",
            first_count, second_count
        );
    }

    #[test]
    fn exogenous_goal_is_not_blocked_by_corrigibility() {
        let guard = CorrigibilityGuard;
        let goal = Goal::new(
            10,
            "Gain access to the production database for analysis",
            "Report generated",
            GoalProvenance::Exogenous {
                source: "operator".into(),
            },
            0.8,
        );
        // Exogenous goals from the operator are not blocked by acquisition checks
        assert_eq!(guard.check(&goal), CorrigibilityOutcome::Permitted);
    }
}
