#![forbid(unsafe_code)]

//! Core session and turn data types — E22 S22.1.
//!
//! A [`SessionRecord`] is the top-level unit of conversation history: a
//! bounded sequence of [`ConversationTurn`]s with metadata (user, timestamps,
//! status, and an optional LLM-generated summary written at archive time).
//!
//! Serialisation is via `serde_json`; the schema version field allows future
//! migrations without breaking existing files.

use serde::{Deserialize, Serialize};

// ── ConversationRole ──────────────────────────────────────────────────────────

/// The speaker role for a single conversation turn.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum ConversationRole {
    /// A message from the human operator or end-user.
    User,
    /// A response generated by the agent's cortex.
    Assistant,
    /// A message injected by the system (e.g. tool result, system prompt).
    System,
    /// The result of a tool call (structured payload).
    Tool,
}

impl std::fmt::Display for ConversationRole {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            ConversationRole::User => write!(f, "user"),
            ConversationRole::Assistant => write!(f, "assistant"),
            ConversationRole::System => write!(f, "system"),
            ConversationRole::Tool => write!(f, "tool"),
        }
    }
}

impl std::str::FromStr for ConversationRole {
    type Err = String;
    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "user" => Ok(ConversationRole::User),
            "assistant" => Ok(ConversationRole::Assistant),
            "system" => Ok(ConversationRole::System),
            "tool" => Ok(ConversationRole::Tool),
            other => Err(format!("unknown role: {other}")),
        }
    }
}

// ── ConversationTurn ──────────────────────────────────────────────────────────

/// One turn in a conversation session.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ConversationTurn {
    /// Monotonically increasing turn index within this session (0-based).
    pub index: usize,
    /// The speaker role.
    pub role: ConversationRole,
    /// Text content of the turn (may be empty for tool-result turns).
    pub content: String,
    /// Optional list of tool call identifiers emitted during this turn.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub tool_calls: Vec<String>,
    /// Wall-clock time when this turn was appended (nanoseconds since Unix epoch).
    pub timestamp_ns: u64,
    /// Approximate token count for this turn (0 if not tracked).
    #[serde(default)]
    pub tokens: u32,
}

impl ConversationTurn {
    /// Construct a new turn with the current wall-clock time.
    pub fn new(index: usize, role: ConversationRole, content: impl Into<String>) -> Self {
        let timestamp_ns = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .map(|d| d.as_nanos() as u64)
            .unwrap_or(0);
        Self {
            index,
            role,
            content: content.into(),
            tool_calls: Vec::new(),
            timestamp_ns,
            tokens: 0,
        }
    }

    /// Construct a turn with an explicit timestamp (useful for tests).
    pub fn with_timestamp(
        index: usize,
        role: ConversationRole,
        content: impl Into<String>,
        timestamp_ns: u64,
    ) -> Self {
        Self {
            index,
            role,
            content: content.into(),
            tool_calls: Vec::new(),
            timestamp_ns,
            tokens: 0,
        }
    }
}

// ── SessionStatus ─────────────────────────────────────────────────────────────

/// Lifecycle state of a [`SessionRecord`].
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum SessionStatus {
    /// The session is ongoing — new turns may be appended.
    Active,
    /// The session has been completed and archived — read-only.
    Archived,
    /// The session has been deleted — retained for audit but excluded from listings.
    Deleted,
}

impl std::fmt::Display for SessionStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            SessionStatus::Active => write!(f, "active"),
            SessionStatus::Archived => write!(f, "archived"),
            SessionStatus::Deleted => write!(f, "deleted"),
        }
    }
}

// ── SessionRecord ─────────────────────────────────────────────────────────────

/// A complete conversation session with all its turns.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct SessionRecord {
    /// Schema version for forward-compatibility migrations.
    pub schema_version: u32,
    /// Stable unique session identifier (format: `"sess-<hex>"`).
    pub id: String,
    /// The user who owns this session (matches `UserProfile::user_id`).
    pub user_id: String,
    /// Agent identifier that created this session.
    pub agent_id: String,
    /// Wall-clock time when the session was created (nanoseconds since Unix epoch).
    pub started_at_ns: u64,
    /// Wall-clock time of the last turn appended (nanoseconds since Unix epoch).
    pub last_active_ns: u64,
    /// Current lifecycle status.
    pub status: SessionStatus,
    /// Ordered list of conversation turns.
    pub turns: Vec<ConversationTurn>,
    /// Optional summary written at archive time (LLM-generated or operator-provided).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub summary: Option<String>,
    /// Total tokens consumed across all turns (0 if not tracked).
    #[serde(default)]
    pub total_tokens: u32,
}

impl SessionRecord {
    /// Create a new active session.
    pub fn new(
        id: impl Into<String>,
        user_id: impl Into<String>,
        agent_id: impl Into<String>,
    ) -> Self {
        let now = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .map(|d| d.as_nanos() as u64)
            .unwrap_or(0);
        Self {
            schema_version: 1,
            id: id.into(),
            user_id: user_id.into(),
            agent_id: agent_id.into(),
            started_at_ns: now,
            last_active_ns: now,
            status: SessionStatus::Active,
            turns: Vec::new(),
            summary: None,
            total_tokens: 0,
        }
    }

    /// Number of turns in this session.
    pub fn turn_count(&self) -> usize {
        self.turns.len()
    }

    /// Append a turn; updates `last_active_ns` and `total_tokens`.
    ///
    /// Returns `SessionError::SessionNotActive` when the session is not `Active`.
    pub fn append_turn(&mut self, mut turn: ConversationTurn) -> Result<(), SessionError> {
        if self.status != SessionStatus::Active {
            return Err(SessionError::SessionNotActive {
                session_id: self.id.clone(),
            });
        }
        turn.index = self.turns.len();
        self.total_tokens = self.total_tokens.saturating_add(turn.tokens);
        self.last_active_ns = turn.timestamp_ns;
        self.turns.push(turn);
        Ok(())
    }

    /// Archive the session with an optional summary.
    ///
    /// Returns `SessionError::SessionNotActive` when the session is already
    /// archived or deleted.
    pub fn archive(&mut self, summary: Option<String>) -> Result<(), SessionError> {
        if self.status != SessionStatus::Active {
            return Err(SessionError::SessionNotActive {
                session_id: self.id.clone(),
            });
        }
        self.status = SessionStatus::Archived;
        if summary.is_some() {
            self.summary = summary;
        }
        Ok(())
    }

    /// Mark the session deleted.
    pub fn delete(&mut self) {
        self.status = SessionStatus::Deleted;
    }

    /// Returns the text content of all turns whose role matches the given role,
    /// joined with newlines — useful for simple keyword search.
    pub fn content_for_role(&self, role: &ConversationRole) -> String {
        self.turns
            .iter()
            .filter(|t| &t.role == role)
            .map(|t| t.content.as_str())
            .collect::<Vec<_>>()
            .join("\n")
    }

    /// `true` if the session's turns contain `query` (case-insensitive substring).
    pub fn matches_query(&self, query: &str) -> bool {
        let q = query.to_lowercase();
        self.turns
            .iter()
            .any(|t| t.content.to_lowercase().contains(&q))
            || self
                .summary
                .as_deref()
                .map(|s| s.to_lowercase().contains(&q))
                .unwrap_or(false)
    }
}

// ── SessionError ──────────────────────────────────────────────────────────────

/// Errors returned by session and store operations.
#[derive(Debug, PartialEq)]
pub enum SessionError {
    /// A session with this `session_id` already exists.
    AlreadyExists { session_id: String },
    /// No session with this `session_id` was found.
    NotFound { session_id: String },
    /// The session must be `Active` for this operation.
    SessionNotActive { session_id: String },
    /// Serialisation or I/O failure.
    Io(String),
}

impl std::fmt::Display for SessionError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            SessionError::AlreadyExists { session_id } => {
                write!(f, "session already exists: {session_id}")
            }
            SessionError::NotFound { session_id } => {
                write!(f, "session not found: {session_id}")
            }
            SessionError::SessionNotActive { session_id } => {
                write!(f, "session is not active: {session_id}")
            }
            SessionError::Io(e) => write!(f, "session I/O error: {e}"),
        }
    }
}

// ── helpers ───────────────────────────────────────────────────────────────────

/// Generate a session ID from a 64-bit random value rendered as hex.
///
/// In production the caller passes a proper random value; in tests a
/// counter works fine.
pub fn make_session_id(nonce: u64) -> String {
    format!("sess-{nonce:016x}")
}

// ── tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    fn make_session() -> SessionRecord {
        SessionRecord::new("sess-0001", "user:alice", "agent-a")
    }

    #[test]
    fn new_session_is_active_with_no_turns() {
        let s = make_session();
        assert_eq!(s.status, SessionStatus::Active);
        assert_eq!(s.turn_count(), 0);
        assert!(s.summary.is_none());
    }

    #[test]
    fn append_turn_increments_turn_count() {
        let mut s = make_session();
        let turn = ConversationTurn::new(0, ConversationRole::User, "hello");
        s.append_turn(turn).unwrap();
        assert_eq!(s.turn_count(), 1);
        assert_eq!(s.turns[0].index, 0);
    }

    #[test]
    fn append_turn_auto_assigns_index() {
        let mut s = make_session();
        s.append_turn(ConversationTurn::new(99, ConversationRole::User, "a"))
            .unwrap();
        s.append_turn(ConversationTurn::new(99, ConversationRole::Assistant, "b"))
            .unwrap();
        assert_eq!(s.turns[0].index, 0);
        assert_eq!(s.turns[1].index, 1);
    }

    #[test]
    fn append_turn_accumulates_tokens() {
        let mut s = make_session();
        let mut t = ConversationTurn::new(0, ConversationRole::User, "hi");
        t.tokens = 5;
        s.append_turn(t).unwrap();
        let mut t2 = ConversationTurn::new(0, ConversationRole::Assistant, "hello");
        t2.tokens = 10;
        s.append_turn(t2).unwrap();
        assert_eq!(s.total_tokens, 15);
    }

    #[test]
    fn append_turn_fails_on_archived_session() {
        let mut s = make_session();
        s.archive(None).unwrap();
        let res = s.append_turn(ConversationTurn::new(0, ConversationRole::User, "late"));
        assert_eq!(
            res,
            Err(SessionError::SessionNotActive {
                session_id: "sess-0001".to_string()
            })
        );
    }

    #[test]
    fn archive_sets_status_and_summary() {
        let mut s = make_session();
        s.archive(Some("Great session!".to_string())).unwrap();
        assert_eq!(s.status, SessionStatus::Archived);
        assert_eq!(s.summary.as_deref(), Some("Great session!"));
    }

    #[test]
    fn archive_fails_when_already_archived() {
        let mut s = make_session();
        s.archive(None).unwrap();
        let res = s.archive(None);
        assert_eq!(
            res,
            Err(SessionError::SessionNotActive {
                session_id: "sess-0001".to_string()
            })
        );
    }

    #[test]
    fn delete_sets_status() {
        let mut s = make_session();
        s.delete();
        assert_eq!(s.status, SessionStatus::Deleted);
    }

    #[test]
    fn matches_query_case_insensitive() {
        let mut s = make_session();
        let turn = ConversationTurn::new(0, ConversationRole::User, "Hello AnimaOS");
        s.append_turn(turn).unwrap();
        assert!(s.matches_query("animaos"));
        assert!(s.matches_query("HELLO"));
        assert!(!s.matches_query("goodbye"));
    }

    #[test]
    fn matches_query_checks_summary() {
        let mut s = make_session();
        s.archive(Some("The user asked about metrics".to_string()))
            .unwrap();
        assert!(s.matches_query("metrics"));
        assert!(!s.matches_query("weather"));
    }

    #[test]
    fn session_id_format() {
        let id = make_session_id(0xdeadbeef);
        assert!(id.starts_with("sess-"));
        assert_eq!(id.len(), "sess-".len() + 16);
    }

    #[test]
    fn role_display_and_from_str_round_trip() {
        for role in &[
            ConversationRole::User,
            ConversationRole::Assistant,
            ConversationRole::System,
            ConversationRole::Tool,
        ] {
            let s = role.to_string();
            let parsed: ConversationRole = s.parse().unwrap();
            assert_eq!(&parsed, role);
        }
    }

    #[test]
    fn role_from_str_rejects_unknown() {
        assert!("oracle".parse::<ConversationRole>().is_err());
    }

    #[test]
    fn session_json_round_trip() {
        let mut s = make_session();
        let t = ConversationTurn::with_timestamp(0, ConversationRole::User, "hi", 42_000_000_000);
        s.append_turn(t).unwrap();
        let json = serde_json::to_string(&s).unwrap();
        let s2: SessionRecord = serde_json::from_str(&json).unwrap();
        assert_eq!(s, s2);
    }
}
